Rework Health routes
KevinRecuerda/RecShark pull request #42
Opened 2022-03-03 08:44 UTC by brandicorel

2022-03-03 16:34 UTC, KevinRecuerda requested changes

2022-03-03 16:34 UTC, KevinRecuerda commented on src/AspNetCore/Configurator/MonitoringConfigurator.HealthCheck.cs
> +        }
maybe we can trash this

2022-03-03 16:34 UTC, KevinRecuerda commented on src/AspNetCore/Configurator/MonitoringConfigurator.HealthCheck.cs
> +            return options.MapHealthChecks(pattern, check => !tags.Any() || tags.Any(tag => check.Tags.Contains(tag)));
could use `ContainsAny`

2022-03-03 16:34 UTC, KevinRecuerda commented on src/AspNetCore/Health/HealthStartupService.cs
> +    public abstract class BaseHealthStartupService : BackgroundService, IHealthStartupService
should we rename `BaseHealthStartupService` &rarr; `StartupBackgroundService` ?

2022-03-03 16:34 UTC, KevinRecuerda commented on src/AspNetCore/Health/HealthStartupService.cs
> +        public abstract Task InnerExecute();
should pass cancellationToken

2022-03-03 16:34 UTC, KevinRecuerda commented on src/AspNetCore/Health/StartupHealthService.cs
> +    public class StartupHealthService : IHealthCheck
could rename `StartupHealthService` &rarr; `StartupHealthChecker`

2022-03-03 16:34 UTC, KevinRecuerda commented on src/AspNetCore/Configurator/MonitoringConfigurator.HealthCheck.cs
> +            services.AddHostedService(sp => sp.GetService<IHealthStartupService>() as TStartupService);
can't register multiple services.
could do that:
```csharp
services.AddSingleton<TStartupService>();
services.Add<IHealthStartupService>((sp => sp.GetService<TStartupService>());
services.AddHostedService(sp => sp.GetService<TStartupService>());
```

2022-03-03 16:34 UTC, KevinRecuerda commented on src/AspNetCore/Configurator/MonitoringConfigurator.HealthCheck.cs
> +        public static void AddStartupHealthService<TStartupService>(this IServiceCollection services)
should we rename to `StartupHostedService` ?

2022-03-03 16:34 UTC, KevinRecuerda commented on src/AspNetCore/Health/StartupHealthService.cs
> +                return Task.FromResult(HealthCheckResult.Healthy("No startup task defined."));
maybe we could remove this part.

2022-03-03 16:34 UTC, KevinRecuerda commented on src/AspNetCore/Configurator/MonitoringConfigurator.HealthCheck.cs
> +                    options.MapHealthChecks("/healthz/startup", "startup");
i think we should add `StartupHealthChecker` by default

2022-03-03 16:36 UTC, brandicorel commented on src/AspNetCore/Configurator/MonitoringConfigurator.HealthCheck.cs
> +        }
I've left it for retro-compatibility but I agree we can remove it.

2022-03-03 16:39 UTC, brandicorel commented on src/AspNetCore/Health/HealthStartupService.cs
> +    public abstract class BaseHealthStartupService : BackgroundService, IHealthStartupService
it's an abstract class, I though usage was to prefix abstract class by "Base"

2022-03-03 20:31 UTC, KevinRecuerda requested changes

2022-03-03 20:31 UTC, KevinRecuerda commented on src/AspNetCore/Configurator/MonitoringConfigurator.HealthCheck.cs
> +            where TStartupHostedService : class, IStartupHostedService
could rename `TStartupHostedService` to `T`
(not easy to distinguish `TStartupHostedService` and `IStartupHostedService`)

2022-03-03 20:31 UTC, KevinRecuerda commented on src/AspNetCore/Configurator/MonitoringConfigurator.HealthCheck.cs
> +                         .AddCheck<StartupHealthChecker>("initialize", tags: new[] {"startup"});
should we name this check `startup` ?

2022-03-03 20:31 UTC, KevinRecuerda commented on sample/AspNetCore.Sample/Startup.cs
> +               .UseEndpoints(endpoints => { endpoints.MapControllers(); });
old way seems more appropriate
(extension only on `endpoints`: `endpoints.MapConventionalHealthChecks()` ?)

2022-03-03 20:31 UTC, KevinRecuerda commented on src/AspNetCore/Health/StartupHealthChecker.cs
> +                return Task.FromResult(HealthCheckResult.Unhealthy("The startup tasks are still running."));
should we list running tasks ?

2022-03-04 16:30 UTC, KevinRecuerda approved these changes

2022-03-04 16:32 UTC, merged