Add polly retry
KevinRecuerda/RecShark pull request #54
Opened 2022-06-02 14:16 UTC by Gafs63

2022-06-07 08:52 UTC, brandicorel approved these changes

2022-06-07 09:07 UTC, KevinRecuerda requested changes

2022-06-07 09:07 UTC, KevinRecuerda commented on src/AspNetCore.ApiClient/AspNetCore.ApiClient.csproj
> +    <Version>1.0.1-beta1</Version>
could be minor version here

2022-06-07 09:07 UTC, KevinRecuerda commented on src/AspNetCore.ApiClient/HttpClientFactoryExtensions.cs
> +        public static ICollection<Func<PolicyBuilder<HttpResponseMessage>, IAsyncPolicy<HttpResponseMessage>>> DefaultPolicies =
could use single object instead of collection

2022-06-07 09:29 UTC, KevinRecuerda commented on src/AspNetCore.ApiClient/HttpClientFactoryExtensions.cs
> +        public static ICollection<Func<PolicyBuilder<HttpResponseMessage>, IAsyncPolicy<HttpResponseMessage>>> DefaultPolicies =
We can wrap inner func if necessary

2022-06-08 08:08 UTC, KevinRecuerda requested changes

2022-06-08 08:08 UTC, KevinRecuerda commented on src/AspNetCore.ApiClient/HttpClientFactoryExtensions.cs
> +            bool                    useDefaultPolicies = true)
```suggestion
            bool                    useDefaultPolicy = true)
```

2022-06-08 08:08 UTC, KevinRecuerda commented on src/AspNetCore.ApiClient/HttpClientFactoryExtensions.cs
> +        private static IHttpClientBuilder AddErrorPolicies(this IHttpClientBuilder builder, bool useDefaultPolicy)
```suggestion
        private static IHttpClientBuilder AddErrorPolicy(this IHttpClientBuilder builder, bool useDefaultPolicy)
```

2022-06-08 08:08 UTC, KevinRecuerda commented on src/AspNetCore.ApiClient/HttpClientFactoryExtensions.cs
> +            builder => builder.WaitAndRetryAsync(new[] {TimeSpan.FromMilliseconds(500)});
maybe, also add circuit breaker as default

2022-06-08 09:14 UTC, KevinRecuerda approved these changes

2022-06-08 09:18 UTC, merged